name = "pancarta-sgb"
main = "index.js"
compatibility_date = "2026-05-26"
account_id = "dc13b2cb0be44bd64e418965f37b4019"
workers_dev = true

[site]
bucket = "."
include = ["**/*"]
exclude = ["wrangler.toml", "package.json", "README-deploy.md", "index.js"]
